apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: confluence
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      run: confluence
    name: confluence
  spec:
     replicas: 1
     selector:
        run: confluence
     strategy:
        type: Recreate
     template:
        metadata:
          labels:
            run: confluence
        spec:
         initContainers:
          - resources: {}
            terminationMessagePath: /dev/termination-log
            name: nfs-permission-fixer
            command:
              - sh
              - '-c'
              - (chgrp 2001 /shared-home; chmod g+w /shared-home)
            securityContext:
              runAsUser: 0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: shared-home
                mountPath: /shared-home
            terminationMessagePolicy: File
            image: alpine
         serviceAccountName: default
         securityContext:
          fsGroup: 2001
         containers:
         - env:
            - name: JVM_XMX
              value: '2048m'
            - name: JVM_XMS
              value: '1024m'
           image: docker.io/atlassian/confluence-server:7.6
           imagePullPolicy: IfNotPresent
           name: confluence
           securityContext:
             capabilities: {}
             privileged: false
           volumeMounts:
            - name: local-home
              mountPath: /var/atlassian/application-data/jira
            - name: local-home
              mountPath: /opt/atlassian/jira/logs
              subPath: log
            - name: shared-home
              mountPath: /var/atlassian/application-data/shared-home
         volumes:
          - name: local-home
            emptyDir: {}
          - name: shared-home
            emptyDir: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      run: mysql
    name: mysql
  spec:
    replicas: 1
    selector:
      run: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          run: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: confluence
          - name: MYSQL_PASSWORD
            value: confluence
          - name: MYSQL_DATABASE
            value: confluence
          - name: MYSQL_ROOT_PASSWORD
            value: confluence
          image: docker.io/mysql:5.6
          imagePullPolicy: IfNotPresent
          name: mysql
          securityContext:
            capabilities: {}
            privileged: false
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: volume-uiwfa
        volumes:
          - name: volume-uiwfa
            persistentVolumeClaim:
              claimName: mysql-data
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: confluence
    name: confluence
  spec:
    ports:
      - port: 8090
        protocol: TCP
        targetPort: 8090
    selector:
      run: confluence
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: mysql
    name: mysql
  spec:
    ports:
      - port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
      run: mysql
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 3000s
    labels:
      run: confluence
    name: confluence
  spec:
    port:
      targetPort: 8090
    to:
      kind: Service
      name: confluence
      weight: 100
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mysql-data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
