apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: confluence-server
    labels:
      app: confluence-server
      app.kubernetes.io/part-of: Infrastructure
  spec:
    replicas: 1
    selector:
      app: confluence-server
      deploymentconfig: confluence-server
    template:
      metadata:
        labels:
          app: confluence-server
          deploymentconfig: confluence-server
      spec:
        volumes:
          - name: confluence-server-1
            emptyDir: {}
          - name: confluence-server-2
            emptyDir: {}
        containers:
          - name: confluence-server
            image: atlassian/confluence-server:7
            ports:
              - containerPort: 8090
                protocol: TCP
              - containerPort: 8091
                protocol: TCP
            resources: {}
            volumeMounts:
              - name: confluence-server-1
                mountPath: /var/atlassian/application-data/confluence
              - name: confluence-server-1
                mountPath: /opt/atlassian/confluence/logs
                subPath: log
              - name: confluence-server-2
                mountPath: /var/atlassian/application-data/shared-home
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: confluence
        securityContext: 
          fsGroup: 2001
        schedulerName: default-scheduler
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: confluence-server
    name: confluence-server
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: confluence-server
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: confluence-server
    name: confluence-server
  spec:
    port:
      targetPort: 8090
    to:
      kind: Service
      name: confluence-server
      weight: 100
kind: List
metadata: {}
