apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: jira-software
    labels:
      app: jira-software
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: jira-software
      spec:
        volumes:
          - name: jira-software-1
            emptyDir: {}
        containers:
          - name: jira-software
            image: atlassian/jira-software:8
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            volumeMounts:
              - name: jira-software-1
                mountPath: /var/atlassian/application-data/jira
              - name: jira-software-1
                mountPath: /opt/atlassian/jira/logs
                subPath: log
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- apiVersion: v1
  kind: Service
  metadata:
    name: jira-software
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: jira-software
    type: ClusterIP

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: jira-software
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: jira-software
      weight: 100
kind: List
metadata: {}
