apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: confluence-server
    labels:
      app: confluence-server
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: confluence-server
      deploymentconfig: confluence-server
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: confluence-server
          deploymentconfig: confluence-server
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        volumes:
          - name: confluence-server-1
            emptyDir: {}
          - name: confluence-server-2
            emptyDir: {}
        containers:
          - name: confluence-server
            image: atlassian/confluence-server:7
            ports:
              - containerPort: 8090
                protocol: TCP
              - containerPort: 8091
                protocol: TCP
            resources: {}
            volumeMounts:
              - name: confluence-server-1
                mountPath: /var/atlassian/application-data/confluence
              - name: confluence-server-1
                mountPath: /opt/atlassian/confluence/logs
                subPath: log
              - name: confluence-server-2
                mountPath: /var/atlassian/application-data/shared-home
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext:
          fsGroup: 2001
        schedulerName: default-scheduler
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: confluence
    name: confluence
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      run: confluence
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 3000s
    labels:
      run: confluence
    name: confluence
  spec:
    port:
      targetPort: 8090
    to:
      kind: Service
      name: confluence
      weight: 100
kind: List
metadata: {}
